### ISSUE TITLE
`npm test` failures

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/forza#34]
@mmalecki any ideas?

``` sh
Running test/start-udp-test.js...

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: 5340 == 5341
    at null.<anonymous> (/Users/jcrugzz/node.js/nodejitsu/forza/test/start-udp-test.js:23:14)
    at null.<anonymous> (/Users/jcrugzz/node.js/nodejitsu/forza/node_modules/assert-called/lib/assert-called.js:7:8)
    at EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at Transform.push (_stream_transform.js:140:32)
    at /Users/jcrugzz/node.js/nodejitsu/forza/node_modules/json-stream/lib/json-stream.js:32:10
    at Array.forEach (native)

  ✗ test/start-udp-test.js (exit code: 8)
```

and

``` sh
Running test/logs-test.js...

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: 0 == 1024
    at Socket.<anonymous> (/Users/jcrugzz/node.js/nodejitsu/forza/test/logs-test.js:28:12)
    at Socket.<anonymous> (/Users/jcrugzz/node.js/nodejitsu/forza/node_modules/assert-called/lib/assert-called.js:7:8)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

  ✗ test/logs-test.js (exit code: 8)
```

**Comment by mmalecki** [comment]
Try killing all your background node and forza processes, tests pass for me on master.

**Comment by jcrugzz** [comment]
Ahh yes I was being foolish. Tests pass
